### ISSUE TITLE
Beam center finder

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/ess-legacy-v2#158]
See https://confluence.esss.lu.se/display/~wojciechpotrzebowski/Beam+Center+Finder.

Related links:

- https://docs.mantidproject.org/nightly/interfaces/isis_sans/Beam%20Centre%20Tab.html
- https://docs.mantidproject.org/nightly/algorithms/SANSBeamFinder-v1.html
- https://docs.mantidproject.org/nightly/algorithms/FindCenterOfMassPosition-v2.html

**Comment by nvaytet** [comment]
I experimented with a few things from `scikit-image`. For instance, using edge detection to fit a circle to rings on an image. This works nicely, even with multiple rings and rings that are incomplete. Here is a short example:
```Py

import numpy as np
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt
from skimage import io, feature, color, measure, draw, img_as_float
from skimage.restoration import estimate_sigma

%matplotlib widget

nx = 1000
ny = 800

image = np.zeros([ny, nx])
gridx, gridy = np.meshgrid(np.arange(nx), np.arange(ny))


# radius = [200, 350]
# thickness = [5, 30]
radius = [200]
thickness = [5]

x = 300
y = 170

for r, t in zip(radius, thickness):
    dist = np.sqrt((gridx - x)**2 + (gridy - y)**2)
    circle = np.abs(dist - r) < t
    image[circle] = 30


smooth = gaussian_filter(image, sigma=10)

noise = 2.0
smooth += np.random.random([ny, nx]) * noise

estimated_noise = estimate_sigma(smooth)
print('estimated_noise', estimated_noise)

edges = feature.canny(smooth, sigma=10)
coords = np.column_stack(np.nonzero(edges))

model, inliers = measure.ransac(coords, measure.CircleModel,
                                min_samples=3, residual_threshold=1,
                                max_trials=1000)

print(model.params)

rr, cc = draw.circle_perimeter(int(model.params[0]),
                               int(model.params[1]),
                               int(model.params[2]),
                               shape=image.shape)

res = smooth.copy()
res[rr, cc] = noise + 10

fig, ax = plt.subplots()
ax.imshow(res, origin='lower')
ax.scatter(model.params[1], model.params[0], s=50, c='red')
```
![Figure 4](https://user-images.githubusercontent.com/39047984/216328803-86895e39-4e1c-4238-9d33-991d6e15920d.png)


However, this just finds the center of a circle on a flat panel. This might be more difficult to achieve with layers of straws.
In addition, this does not take into account things like gravity correction.

The goal of the beam centre finder is to make sure that the I(Q) distribution is isotropic, so that we can average around the Phi angle. The best way is probably, as suggested by Richard and is implemented in the ISIS Mantid algorithm, to compute the I(Q) in sections of Phi, and make sure all curves look the same by iterating over `x` and `y` offsets until convergence is found.

We can start with 4 quadrants, as currently done in SANS2D:
![fig4_2](https://user-images.githubusercontent.com/39047984/216330757-f337d8a4-fbcc-45c4-9507-f791eed084fe.png)

Are more than 4 quadrants required?

**Comment by SimonHeybrock** [comment]
What is wrong with the existing algorithm proposed in the requirement?

**Comment by nvaytet** [comment]
Nothing, this is what we will implement. I was just looking at alternatives, to see if something could be used from the python ecosystem.
I updated my comment to say that this is also what is implemented in the Mantid algorithms.
